---
# Initial model setup
sensor_properties: '/var/root/PycharmProjects/metec_model/Resources/sensor_properties_test.csv'
pins_to_registers: '/var/root/PycharmProjects/metec_model/Resources/pins_to_registers.csv'
volumes_files:
  - '/var/root/PycharmProjects/metec_model/Resources/GSH-1-volumes.json'
  - '/var/root/PycharmProjects/metec_model/Resources/GSH-2-fake-volumes.json'
  - '/var/root/PycharmProjects/metec_model/Resources/GSH-3-fake-volumes.json'
  - '/var/root/PycharmProjects/metec_model/Resources/GSH-4-fake-volumes.json'
Labjacks:
  # GSH-1
  GSH-1.LJ-1:
    port: 501
  CB-1W.LJ-1:
    port: 502
  CB-1T.LJ-1:
    port: 503
  CB-1S.LJ-1:
    port: 504
  CB-2W.LJ-1:
    port: 505
  CB-2T.LJ-1:
    port: 506
  CB-2S.LJ-1:
    port: 507
  # GSH-2
  GSH-2.LJ-1:
    port: 508
  CB-3W.LJ-1:
    port: 509
  CB-3S.LJ-1:
    port: 510
  CB-3T.LJ-1:
    port: 511
  CB-4W.LJ-1:
    port: 512
  CB-4S.LJ-1:
    port: 513
  CB-4T.LJ-1:
    port: 514
  # GSH-3
  GSH-3.LJ-1:
    port: 515
  CB-5W.LJ-1:
    port: 516
  CB-5S.LJ-1:
    port: 517
  CB-5T.LJ-1:
    port: 518
  CB-6W.LJ-1:
    port: 519
  CB-6S.LJ-1:
    port: 520
  CB-6T.LJ-1:
    port: 521
  # GSH-4
  GSH-4.LJ-1:
    port: 522
  CB-7W.LJ-1:
    port: 523
  CB-7S.LJ-1:
    port: 524
  CB-7T.LJ-1:
    port: 525
  CB-8W.LJ-1:
    port: 526
  CB-8S.LJ-1:
    port: 527
  CB-8T.LJ-1:
    port: 528
valve_states:
  GSH-1.EV-1: open
  GSH-2.EV-1: open
  GSH-3.EV-1: open
  GSH-4.EV-1: open
  CB-3W.EV-11: open
  CB-3W.EV-12: open
  CB-3W.EV-13: open
  CB-3W.EV-21: open
  CB-3W.EV-23: open
#component_failures:
#  CB-1W.EV-11:
#    default: 0.3
#  CB-1W.TC-1:
#    random: 0.6
#  CB-1W.PT-1:
#    dead: 1.0
#  CB-1S.TC-1:
#    NaN: 0.5
gashouses:
  GSH-1:
    - 'CB-1W'
    - 'CB-1S'
    - 'CB-1T'
    - 'CB-2W'
    - 'CB-2S'
    - 'CB-2T'
  GSH-1_FM:
    - 'FM-1'
    - 'FM-2'
    - 'FM-3'
    - 'FM-4'
  GSH-2:
    - 'CB-3W'
    - 'CB-3S'
    - 'CB-3T'
    - 'CB-4W'
    - 'CB-4S'
    - 'CB-4T'
  GSH-2_FM:
    - 'FM-1'
    - 'FM-2'
    - 'FM-3'
    - 'FM-4'
  GSH-3:
    - 'CB-5W'
    - 'CB-5S'
    - 'CB-5T'
    - 'CB-6W'
    - 'CB-6S'
    - 'CB-6T'
  GSH-3_FM:
    - 'FM-1'
    - 'FM-2'
    - 'FM-3'
    - 'FM-4'
  GSH-4:
    - 'CB-7W'
    - 'CB-7S'
    - 'CB-7T'
    - 'CB-8W'
    - 'CB-8S'
    - 'CB-8T'
  GSH-4_FM:
    - 'FM-1'
    - 'FM-2'
    - 'FM-3'
    - 'FM-4'
initial_temperatures:
  GSH-1: 75
  GSH-2: 75
  GSH-3: 75
  GSH-4: 75
initial_pressures:
  GSH-1: 50
  GSH-2: 40
  GSH-3: 30
  GSH-4: 30
# model specific config parameters
localhost: false
socket_type: UDP
noise_factor: 0.01